### ISSUE TITLE
Can't build: libc version conflict

### ISSUE THREAD

**Issue by ligthyear** [maidsafe/safe_core#316]
Trying to build the latest checkout via `cargo build --features "use-mock-routing"` dies with a version conflict on libc:

```
 safe_core @(master ✔) $ cargo build --features "use-mock-routing"
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `libc` (required by `crust`):
all possible versions conflict with previously selected versions of `libc`
  version 0.2.14 in use by libc v0.2.14
  possible versions to select: 0.2.15
```

Switching libc in the `cargo.toml` to `0.2.15` breaks the dependency with `time`:

```
 safe_core @(master ✔) $ cargo build --features "use-mock-routing"
    Updating registry `https://github.com/rust-lang/crates.io-index`
error: failed to select a version for `libc` (required by `safe_core`):
all possible versions conflict with previously selected versions of `libc`
  version 0.2.14 in use by libc v0.2.14
  possible versions to select: 0.2.15
```

But you can't bump that, as it is the latest version of time (0.1.35)

How do/did you successfully compile this?

---

Note: appears to compile fine with version `0.18.0` (using the git-tag).

**Comment by Fraser999** [comment]
Does running `cargo update` then rebuilding fix this?

**Comment by ligthyear** [comment]
@Fraser999 it does indeed. Confused on the why. but Closing the ticket then.

THANKS HEAPS!
