### ISSUE TITLE
test fail with signal: 11, SIGSEGV: invalid memory reference

### ISSUE THREAD

**Issue by ligthyear** [maidsafe/safe_core#340]
Just did a `git pull` on master and then built and ran the tests with `use-mock-rounting` (as the README.md tells me to), just to run into an ugly
```log
...
test ffi::low_level_api::cipher_opt::tests::app_0_to_app_0_sym ... ok
error: Process didn't exit successfully: `/Users/ben/dev/maidsafe/safe_core/target/debug/safe_core-247524a18b5d49eb` (signal: 11, SIGSEGV: invalid memory reference)

Caused by:
  Process didn't exit successfully: `/Users/ben/dev/maidsafe/safe_core/target/debug/safe_core-247524a18b5d49eb` (signal: 11, SIGSEGV: invalid memory reference)
```

[here is the entire log for your inspection](https://github.com/maidsafe/safe_core/files/489082/reference_errors_log.txt)

----

I thought these are the kind of errors we can prevent by using Rust. I guess doing FFI makes the system vulnerable in the same matter again...?

**Comment by Viv-Rajkumar** [comment]
From the logs:

> warning: crate-type "cdylib" was not one of lib|rlib|dylib|staticlib

Guess you're on an older version of rust. An update might be needed.
```
> rustc --version
rustc 1.11.0 (9b21dcd6a 2016-08-15)
```

Does it still occur with rust `1.11`?

**Comment by ligthyear** [comment]
My version is 1.10:
```
 safe_core @(eb172c2 ✗) $ rustc --version
rustc 1.10.0 (cfcb716cf 2016-07-03)
```

**Comment by madadam** [comment]
Can't reproduce. `rustc 1.11.0 (9b21dcd6a 2016-08-15)`.

Also: you can avoid this kind of error if you limit yourself to safe rust. FFI is hard (impossible?) to do without unsafe, unfortunately.

**Comment by ligthyear** [comment]
I can try upgrading my rust, though arguable one from July isn't really "old" in any sense and I'd really prefer to not have soo much super unsafe FFI in the first place.. I'll report back after trying with an upgrade.

**Comment by Viv-Rajkumar** [comment]
> though arguable one from July isn't really "old" in any sense

That is wayyy old in rust world lol. In this case it boils down to the stable version not being compatible with the lib type which the warning specifies. So not much abt the time than what features it supports / lib requires.

> I'd really prefer to not have soo much super unsafe FFI in the first place

I think thats what everyone would prefer ideally. so keeping C layer minimal is something that is always desirable.

**Comment by ligthyear** [comment]
Yeah, appears to work now with `1.11`


I suppose that means the ticket can be closed. Although it makes me rather uncomfortable with this situation.


> That is wayyy old in rust world lol. 

I disagree. For new features, maybe – things are moving fast. But if that was the case here, compiling shouldn't have succeeded at all IMHO. A main promise after all is "If it compiles, it runs" and a common subject at RustFest last week was that there are no known cases of anything that compiled at 1.0 that at any point stopped compiling/working. There is a strong sense of stability in it. 

>  I think thats what everyone would prefer ideally. so keeping C layer minimal is something that is always desirable.

Or non-existant in the first place?!?. I'd still argue that the http-api is better suited in Rust itself rather than in the launcher and that we should remove the FFI layer almost all together – force everyone to either use Rust, too or go through the http-api (which already today is the preferred modus operandi.) without having to have a screen and a launcher. But that's a conversation for a different place.
